app/__init__.py
from flask import Flask
import os
import ConfigParser
from flask.ext.pymongo import PyMongo
from logging.handlers import RotatingFileHandler
from utils.utils import Utils

# Create MongoDB database object.
mongo = PyMongo()
utils = Utils()

def create_app():

    #Here we  create flask app
    app = Flask(__name__)

    #We load configurations
    load_config(app)

    #Configure logging
    configure_logging(app)

    #Import blueprint modules
    from app.mod_map.views import mod_map
    from app.mod_api.views import mod_api

    app.register_blueprint(mod_map)
    app.register_blueprint(mod_api)

    #Initialize the app to work with MongoDB
    mongo.init_app(app, config_prefix='MONGO')

    return app


def load_config(app):
    ''' Reads the config file and loads configuration properties into the Flask app.
    :param app: The Flask app object.
    '''
    # Get the path to the application directory, that's where the config file resides.
    par_dir = os.path.join(__file__, os.pardir)
    par_dir_abs_path = os.path.abspath(par_dir)
    app_dir = os.path.dirname(par_dir_abs_path)

    # Read config file
    config = ConfigParser.RawConfigParser()
    config_filepath = app_dir + '/config.cfg'
    config.read(config_filepath)

    app.config['SERVER_PORT'] = config.get('Application', 'SERVER_PORT')
    app.config['MONGO_DBNAME'] = config.get('Mongo', 'DB_NAME')

    # Logging path might be relative or starts from the root.
    # If it's relative then be sure to prepend the path with the application's root directory path.
    log_path = config.get('Logging', 'PATH')
    if log_path.startswith('/'):
        app.config['LOG_PATH'] = log_path
    else:
        app.config['LOG_PATH'] = app_dir + '/' + log_path

    app.config['LOG_LEVEL'] = config.get('Logging', 'LEVEL').upper()


def configure_logging(app):
    ''' Configure the app's logging.
     param app: The Flask app object
    '''

    log_path = app.config['LOG_PATH']
    log_level = app.config['LOG_LEVEL']

    # If path directory doesn't exist, create it.
    log_dir = os.path.dirname(log_path)
    if not os.path.exists(log_dir):
        os.makedirs(log_dir)

    # Create and register the log file handler.
    log_handler = RotatingFileHandler(log_path, maxBytes=250000, backupCount=5)
    log_handler.setLevel(log_level)
    app.logger.addHandler(log_handler)

    # First log informs where we are logging to. Bit silly but serves  as a confirmation that logging works.
    app.logger.info('Logging to: %s', log_path)

app/mod_api/views.py
from flask import Blueprint, render_template
from flask.views import View
from flask import Response
from bson import json_util
from bson.son import SON
from app import mongo

mod_api = Blueprint('api', __name__, url_prefix = '/api')

@mod_api.route('/routes/<route_slug>', methods=['GET'])
def route(route_slug):

	'''
	Hardcoded for now, but this should be a MongoDB query
	that fetches the document where { 'slug': route_slug }
	'''

	docs = mongo.db.wasteroutes.aggregate([
		{
			"$match":{
				"route.slug": route_slug
			}
		},
		{
			"$group":{
				"_id":{
				 	"rank":"$rank",
				 	"lat": "$lat",
				 	"lng": "$lng"
				},
				"count":{
					"$sum":1
				}
			}
		},
		{
			"$sort": {
				"_id.rank": 1
			}	
		},
		{
			"$project":{
				"_id": 0,
				"lat":"$_id.lat",
				"lng":"$_id.lng",
				"count":"$count"
			}	
		}
	])

	result = docs['result']


	resp = Response(
            response=json_util.dumps(result),
            mimetype='application/json')

	return resp

app/mod_map/views.py
from flask import Blueprint, render_template
from flask.views import View

from app import mongo

mod_map = Blueprint('map', __name__)

@mod_map.route('/', methods=['GET'])
def map():
    '''
    Show map page.
    '''
    return render_template('mod_map/map.html')

@mod_map.route('/statistics', methods=['GET'])
def statistics():
    '''
    Show statistics page.
    '''
    return render_template('mod_map/statistics.html')

@mod_map.route('/about', methods=['GET'])
def about():
    '''
    Show about page.
    '''
    return render_template('mod_map/about.html')

@mod_map.route('/testimonials', methods=['GET'])
def testimonials():
    '''
    Show testimonials page.
    '''
    return render_template('mod_map/testimonials.html')

@mod_map.route('/video', methods=['GET'])
def video():
    '''
    Show video page.
    '''
    return render_template('mod_map/video.html')

app/templates/layout.html
<html>

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Illegal Dumps</title>

    <script type="text/javascript" src="https://www.google.com/jsapi"></script>

    <!-- Bootstrap Core CSS -->
    <link href="{{ url_for('static', filename='startbootstrap/css/bootstrap.min.css') }}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{{ url_for('static', filename='startbootstrap/css/agency.css') }}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{{ url_for('static', filename='startbootstrap/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

    <!-- Custom CSS -->
    <link href="{{ url_for('static', filename='style.css') }}" rel="stylesheet">

    <!-- Google Analytics -->
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-59188119-2', 'auto');
      ga('send', 'pageview');

    </script>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- jQuery -->
    <script src="{{ url_for('static', filename='startbootstrap/js/jquery.js') }}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{{ url_for('static', filename='startbootstrap/js/bootstrap.min.js') }}"></script>

</head>

<body id="page-top" class="index">

    <!-- Navigation -->
        <nav class="navbar navbar-default navbar-fixed-top navbar-shrink">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <a class="navbar-brand">Illegal Dumps</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ url_for('map.map') }}">Map</a></li>
                    <li><a href="{{ url_for('map.statistics') }}">Statistics</a></li>
                    <li><a href="{{ url_for('map.video') }}">Video</a></li>
                    <li><a href="{{ url_for('map.testimonials') }}">Testimonials</a></li>
                    <li><a href="{{ url_for('map.about') }}">About</a></li>
                </ul>

            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
    {% block body %}
    {% endblock %}
    {#
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <span class="copyright"><a href="http://opendatakosovo.org/data">Data</a></span>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline social-buttons">
                        <li>
                            <a href="http://opendatakosovo.org/">
                                <i class="fa fa-globe"></i>
                            </a>
                        </li>
                        <li>
                            <a href="https://www.facebook.com/opendatakosovo">
                                <i class="fa fa-facebook"></i>
                            </a>
                        </li>
                        <li>
                            <a href="https://twitter.com/OpenDataKosovo">
                                <i class="fa fa-twitter"></i>
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline quicklinks">
                        <li><a href="https://github.com/opendatakosovo/illegal-dump-tracker">Source Code</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    #}

    
    <!-- Plugin JavaScript -->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="{{ url_for('static', filename='startbootstrap/js/classie.js') }}"></script>

    <!-- Don't want navbar animation -->
    <!--script src="{{ url_for('static', filename='startbootstrap/js/cbpAnimatedHeader.js') }}"></script-->
    

    <!-- Contact Form JavaScript 
    <script src="{{ url_for('static', filename='startbootstrap/js/jqBootstrapValidation.js') }}"></script>
    <script src="{{ url_for('static', filename='startbootstrap/js/contact_me.js') }}"></script> -->

    <!-- Custom Theme JavaScript -->
    <script src="{{ url_for('static', filename='startbootstrap/js/agency.js') }}"></script>

</body>

</html>

app/templates/mod_map/about.html
{% extends "layout.html" %}
{% block body %}
<!-- About Section -->
<section id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">It only took 7 days</h2>
                <h3 class="section-subheading text-muted">
                    A partnership between local youths, Open Data Kosovo, and UNDP/SDC under the SAEK project.
                </h3>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <ul class="timeline">
                    <li>
                        <div class="timeline-image">
                            <img class="img-circle img-responsive" src="{{ url_for('static', filename='img/bedri-cahani.png') }}" alt="">
                        </div>
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h4>Youth Engagement</h4>
                                <h4 class="subheading">Local Communities</h4>
                            </div>
                            <div class="timeline-body">
                                <p class="text-muted">We reached out to local communities for volunteer data collectors. Mr Bedri Cahani, director of the "Hajdar Dushi" school, even involved his students.</p>
                            </div>
                        </div>
                    </li>
                    <li class="timeline-inverted">
                        <div class="timeline-image">
                            <img class="img-circle img-responsive" src="{{ url_for('static', filename='img/small-team.png') }}" alt="">
                        </div>
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h4>Small Teams</h4>
                                <h4 class="subheading">Big Results</h4>
                            </div>
                            <div class="timeline-body">
                                <p class="text-muted">We organized ourselves in small teams of 2 or 3, totalling 30 volunteers. Each team was assigned a geographical zone to spot and report illegal dumping sites.</p>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="timeline-image">
                            <img class="img-circle img-responsive" src="{{ url_for('static', filename='img/trashout-app.png') }}" alt="">
                        </div>
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h4>Leveraging Reusability</h4>
                                <h4 class="subheading">The TrashOut App</h4>
                            </div>
                            <div class="timeline-body">
                                <p class="text-muted">No need to re-invent the wheel when we can re-use proven data collection solutions. TrashOut is an already existing world initiative to locate and report all illegal dumps.</p>
                            </div>
                        </div>
                    </li>
                    <li class="timeline-inverted">
                        <div class="timeline-image">
                            <img class="img-circle img-responsive" src="{{ url_for('static', filename='img/old-school.png') }}" alt="">
                        </div>
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h4>Don't Fear The Analog</h4>
                                <h4 class="subheading">Old School</h4>
                            </div>
                            <div class="timeline-body">
                                <p class="text-muted">When the TrashOut app wasn't compatible with some of our smartphones, we simply collected data the old school way; with clipboards, printed maps, and pens.</p>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="timeline-image">
                            <img class="img-circle img-responsive" src="{{ url_for('static', filename='img/cabrati.png') }}" alt="">
                        </div>
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h4>Reusing Open Data</h4>
                                <h4 class="subheading">The More the Merrier</h4>
                            </div>
                            <div class="timeline-body">
                                <p class="text-muted">The municipality's waste management company had recently opened data on its garbage truck routes so we incorporated those as well.</p>
                            </div>
                        </div>
                    </li>
                    <li class="timeline-inverted">
                        <div class="timeline-image">
                            <img class="img-circle img-responsive" src="{{ url_for('static', filename='img/heatmap.png') }}" alt="">
                        </div>
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h4>Rapid Prototyping</h4>
                                <h4 class="subheading">From Data to Insight</h4>
                            </div>
                            <div class="timeline-body">
                                <p class="text-muted">We played with the data as soon as it was colleced and experimented with neat visualizations when, all of a sudden, we ended up with this neat prototype!</p>
                            </div>
                        </div>
                    </li>
                    <li class="timeline-inverted">
                        <div class="timeline-image">
                            <h4>It's time
                                <br>to clean
                                <br>Gjakova!</h4>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</section>
{% endblock %}

app/templates/mod_map/map.html
{% extends "layout.html" %}
{% block body %}
<!-- leaflets CSS -->
<link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.css" />
<link rel="stylesheet" href="{{ url_for('static', filename='leaflet.fullscreen-1.1.4/Control.FullScreen.css') }}" />
<link rel="stylesheet" href="{{ url_for('static', filename='map-controls/map-controls.css') }}" />
<link rel="stylesheet" href="{{ url_for('static', filename='waitMe/waitMe.min.css') }}" />

<!-- leaflets JS -->
<script src="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.js"></script>
<script src="{{ url_for('static', filename='leaflet.fullscreen-1.1.4/Control.FullScreen.js') }}"></script>
<script src="{{ url_for('static', filename='leaflet-heat.js') }}"></script>
<script src="{{ url_for('static', filename='map-controls/map-controls.js') }}"></script>
<script src="{{ url_for('static', filename='waitMe/waitMe.min.js') }}"></script>

<script src="{{ url_for('static', filename='data/dumps.js') }}"></script>

{# All our routes: id, name, polyline colour, display #}
{%
  set routes = [
    ['ford-03-462-ck','Ford 03-462 CK','green', True],
    ['hunday-ku-03724dp','Hyundai 03-724 DP','yellow', False],
    ['hunday-qe-03679dp','Hyundai 03-679 DP','red', True],
    ['hunday-shp-03682dp','Hyundai 03-682 DP','blue', True],
    ['hyundai-m-thaqi','Hyundai M. Thaqi','magenta', True],
    ['iveco-03804am','Iveco 03-804 AM','black', True],
    ['iveco-a-shala','Iveco A. Shala','brown', True],
    ['iveco','Iveco','grey', True],
    ['man-kalter-03817ce','Man Kalter 03-817 CE','tomato', True],
    ['merc-fek-03584cl','Mercedes Fek 03-584 CL','thistle', False],
    ['merc-kalt-03-802-am','Mercedes Kalt 03-802 AM','deeppink ', True],
    ['merc-kombi-03849ae','Mercedes Kombi 03-849 AE','indianred', True],
    ['merc-port-03801am','Mercedes Port 03-801 AM','magenta ', True]
  ]
%}

<script>
  var map = undefined;
  var COVERED_DAYS = 800;

  var routeLayerGroups = {
    {% for route in routes %}
    '{{ route[0] }}': {
      'layergroup': {
        'route': undefined,
        'heat': undefined
      },
      'color': '{{ route[2] }}',
      'cached': false
    },
    {% endfor %}
  };

  var dumpMarkersLayerGroup = undefined;
  var heatLayerGroup = undefined;

  $(document).ready(function(){
    map = L.map('map', {zoomControl: false}).setView([42.37623671900732, 20.424699783325195], 15);

    L.tileLayer('http://{s}.tiles.mapbox.com/v3/georges.jjc3k7b1/{z}/{x}/{y}.png', {
        attribution: 'Data Source: <a href="http://opendatakosovo.org">Open Data Kosovo</a>',
        maxZoom: 20
    }).addTo(map);

    new L.Control.Zoom({ position: 'topright' }).addTo(map);

    // create a fullscreen button and add it to the map
    L.control.fullscreen({
      position: 'topright', // change the position of the button can be topleft, topright, bottomright or bottomleft, defaut topleft
      title: 'Full screen', // change the title of the button, default Full Screen
      forceSeparateButton: true, // force seperate button to detach from zoom buttons, default false
      forcePseudoFullscreen: true // force use of pseudo full screen even if full screen API is available, default false
    }).addTo(map);

    toggleDumpHeatMap(true);


  });

  function toggleDumpMarkers(display){
    
    if(display == false && dumpMarkersLayerGroup != undefined){
        map.removeLayer(dumpMarkersLayerGroup);

    }else if(dumpMarkersLayerGroup == undefined){

        // First time building this layer, let's do it
        var dumpMarkerArray = [];

        $(dumps).each(function( idx, dump ) {

          daysSinceReported = getDaysSinceReported(dump);

          // Only report trash reported x days from now
          if(daysSinceReported < COVERED_DAYS){

            lat = dump["location"]["lat"];
            lng = dump["location"]["lon"];

            var marker = L.marker([lat, lng]);
            popupHtml = buildMarkerPopup(dump["size"], dump["type"], dump['imgUrl']);

            marker.bindPopup(popupHtml);
            dumpMarkerArray.push(marker);      
          }
        });

        dumpMarkersLayerGroup = L.layerGroup(dumpMarkerArray);
        map.addLayer(dumpMarkersLayerGroup);

    }else{
      // Layer was already previously built, just re-add it.
      map.addLayer(dumpMarkersLayerGroup);
    }  
  }

  function getDaysSinceReported(dump){
    var daysSinceReported = -1

    // For reports not recorded with the TrashOut app, we don't have data on the saved time.
    if("trashTime" in dump){
      daysSinceReported = (new Date().getTime() - dump["trashTime"]["savedTime"]) / (1000*60*60*24);
    }

    return daysSinceReported
  }


  function buildMarkerPopup(dumpSize, dumpTypes, imgUrl){
    // First build the HTML list of dump types.
    var dumpTypeListHtml = "";

    if(dumpTypes.length > 1){ 
      var dumpTypeListHtml = "<ul>";
      for (index = 0; index < dumpTypes.length; index++) {
        dumpTypeListHtml = dumpTypeListHtml + "<li>" + capitalizeFirstLetter(dumpTypes[index]);
      }
      dumpTypeListHtml = dumpTypeListHtml + "</ul>";
    }else{
      dumpTypeListHtml = capitalizeFirstLetter(dumpTypes[0]);
    }

    // Noe build the popup.    
    var markerPopupHtml = "<a href ='" + imgUrl + "'" + " target='_blank'>" + 
      "<img style = 'width: 200' src=" + imgUrl + ">" + 
    "</a><br><br>" +
    "<label>Size:</label> " + capitalizeFirstLetter(dumpSize) + "<br>" +
    "<label>Type:</label> " + dumpTypeListHtml;

    return markerPopupHtml;
  }

  // All the letters of dump size and type words are capitalized.
  // We fix that here. e.g. 
  function capitalizeFirstLetter(str){
    return str.charAt(0) + str.toLowerCase().substring(1);
  }

  function toggleDumpHeatMap(display){
    var heatPoints = [];

    if(display == false && heatLayerGroup != undefined){
        map.removeLayer(heatLayerGroup);
    }else{

      $(dumps).each(function( idx, dump ) {

        daysSinceReported = getDaysSinceReported(dump);

        // Only report trash reported x days from now
        if(daysSinceReported < COVERED_DAYS){
          lat = dump["location"]["lat"];
          lng = dump["location"]["lon"];

          var heatLatLng = new L.LatLng(lat, lng);
          heatPoints.push(heatLatLng);
        }
      });

      var options = {
        'minOpacity': 0.1,
        'max': 0.2,
        'radius': 20,
        'blur': 15
      }

      heatLayerGroup = L.heatLayer(heatPoints, options)
      map.addLayer(heatLayerGroup);
    }
  }

  function toggleTruckRoute(routeSlug, display, mapType){

    if(display == false && routeLayerGroups[routeSlug]['layergroup'][mapType] != undefined){
        map.removeLayer(routeLayerGroups[routeSlug]['layergroup'][mapType]);
    }else{

      // This request for route coordinates hasn't been done before, do it now.
      if(routeLayerGroups[routeSlug]['cached'] == false){
        // Get route data points, build layer, and display it.
        getAndDisplayTruckRouteData(routeSlug, mapType);

      }
      // We have the points/data, it was retrieved when building either the route polyline or route heatmap layer.
      // But now, we are builing the layer we didn't build before, so we still have to build a layer.
      // e.g. First request was for polyline route for truck, got the data and built that layer.
      //      But now the second request is for the heat route for the same truck, got the data but didn't build that layer yet.
      else if(routeLayerGroups[routeSlug]['layergroup'][mapType] == undefined){
        if(mapType == 'route'){
          buildTruckRoutePolylineLayer(routeSlug, routeLayerGroups[routeSlug]['data']);
        }else if(mapType == 'heat'){
          buildTruckRouteHeatLayer(routeSlug, routeLayerGroups[routeSlug]['data']);
        }
      }else{
        // This request for route coordinates has been done before.
        // This means that this route layer has already been built.
        // Retrieve the layer from client-side javascript cache
        map.addLayer(routeLayerGroups[routeSlug]['layergroup'][mapType]);
      }
    }
  }

  function getAndDisplayTruckRouteData(routeSlug, mapType){
    toggleSpinner(true);

    $.get( "{{ url_for('api.route', route_slug='') }}" + routeSlug, function( points ) {

          // Save coordinates for future call.
          // This is so that we don't have to make a request to the server every time.
          // A form of client-side javascript caching.
          // (Maybe it would be better to just "hide" the layer after it is built instead of removing it?)
          routeLayerGroups[routeSlug]['data'] = points;
          routeLayerGroups[routeSlug]['cached'] = true;

    }).done(function() {
        // Build the route layer.
        if(mapType == 'route'){
          buildTruckRoutePolylineLayer(routeSlug, routeLayerGroups[routeSlug]['data']);
        }else if(mapType == 'heat'){
          buildTruckRouteHeatLayer(routeSlug, routeLayerGroups[routeSlug]['data']);
        }

        toggleSpinner(false);   
    });
  }

  function buildTruckRoutePolylineLayer(route_slug, points){

    // Build route polyline layer
    var routeCoordinates = [];

    $(points).each(function( idx, point ) {
      var pointLatLng = new L.LatLng(point.lat, point.lng);
      routeCoordinates.push(pointLatLng);
    });

    var routePolyline = new L.Polyline(routeCoordinates, {
      color: routeLayerGroups[route_slug]['color'],
      weight: 3,
      opacity: 0.5,
      smoothFactor: 1
    });

    routeLayerGroups[route_slug]['layergroup']['route'] = routePolyline;
    map.addLayer(routeLayerGroups[route_slug]['layergroup']['route']);
  }

  function buildTruckRouteHeatLayer(route_slug, points){

    // Build route heat map layer
    var routeCoordinates = [];

    $(points).each(function( idx, point ) {
      var pointLatLng = new L.LatLng(point.lat, point.lng);
      routeCoordinates.push(pointLatLng);
    });

    var options = {
      'minOpacity': 0.1,
      'max': 0.2,
      'radius': 10,
      'blur': 15,
      'gradient': {0.29: 'blue', 0: 'purple', 0.9: 'green'}
    }

    routeLayerGroups[route_slug]['layergroup']['heat'] = L.heatLayer(routeCoordinates, options)
    map.addLayer(routeLayerGroups[route_slug]['layergroup']['heat']);
  }

  function toggleSpinner(display){
    if(display == true){
      $('body').waitMe({
        //none, rotateplane, stretch, orbit, roundBounce, win8, 
        //win8_linear, ios, facebook, rotation, timer, pulse, 
        //progressBar, bouncePulse or img
        effect: 'stretch',
        text: '', //place text under the effect (string).
        bg: 'rgba(255,255,255,0.7)', //background for container (string).
        color: '#000', //color for background animation and text (string).
        sizeW: '', //change width for elem animation (string).
        sizeH: '', //change height for elem animation (string).
        // url to image
        source: 'http://4206e9.medialib.glogster.com/media/0de16589e28c077f3ed220e39400774bac8f7465c318d7fe4cc8e9ce8756e1af/animated-gifs-eagles-6.gif'
      });
    }else{
      $('body').waitMe('hide');
    }
  } 

</script>

<!-- body has the class "cbp-spmenu-push" -->
<nav class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-left" id="cbp-spmenu-s1">
  <ul>
    <li id="menuTitle" class="cbp-spmenu-title"><b>Map Controls<b>
      <span id="showLeft" class="showLeft">&laquo;<span>
    </li>
    <li class="cbp-spmenu-vertical-item-parent" id="dumps">Illegal Dumps</li>
    <li class="cbp-spmenu-vertical-item-child" id="dumps">
      <input type="checkbox" id="markers" name="cc" value="markers" class="dump-checkbox" />
      <label for="markers"><span></span>Markers</label>
      <br>
      <input type="checkbox" id="heat" name="cc" value="heat" class="dump-checkbox" checked />
      <label for="heat"><span></span>Heat Map</label>
    </li>
    </li>

    {% for route in routes %}
      {% if route[3] %}
      <li class="cbp-spmenu-vertical-item-parent" id="{{ route[0] }}">
        {{ route[1] }}
      </li>
      <li class="cbp-spmenu-vertical-item-child"  id="{{ route[0] }}" style="display:none;">
        <input type="checkbox" id="{{ route[0] }}-route" name="{{ route[0] }}" value="{{ route[0] }}" class="route-checkbox"/>
        <label for="{{ route[0] }}-route"><span></span>Route</label>
        <br>
        <input type="checkbox" id="{{ route[0] }}-heat" name="cc" value="{{ route[0] }}" class="route-heat-checkbox" />
        <label for="{{ route[0] }}-heat"><span></span>Heat Map</label>
      </li>
      {% endif %}
    {% endfor %}
  </ul>
</nav>

<div class="map-container">
  <div id="map" style="height:100%;">
  </div>
</div>

{% endblock %}

app/templates/mod_map/video.html
{% extends "layout.html" %}
{% block body %}

<section id="team" class="bg-light-gray">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">A Call for Action</h2>
                <h3 class="section-subheading text-muted">Video production by our talented volunteers.</h3>
            </div>
        </div>
        <div class="row">
        	<div class="col-lg-12 text-center">
        		<iframe width="760" height="515" src="https://www.youtube.com/embed/tcFRGCZj0OM?cc_load_policy=1" frameborder="0" allowfullscreen></iframe>
        	</div>
        </div>
    </div>
</section>

{% endblock %}